### ISSUE TITLE
Replybot goofs up when the SQL database has over 200 entries

### ISSUE THREAD

**Issue by zatherz** [voussoir/reddit#12]
So, the function that's supposed to clean up the old values from the SQL database actually seems to be removing everything after 200. Meaning that the 201th post will receive an insane number of replies from the bot, with it posting once every 10 cycles.

**Comment by voussoir** [comment]
This is strange, and I'm surprised to be hearing about this for the first time just now if it's true.

I just did a test in the interpreter using hypothetical ID numbers, and this is what I got: http://hastebin.com/secidorawe

From this sample you can see it's only keeping the newest 200 items, and when I add a new item "faf", the oldest item "ed8" gets removed during the next cleanup. Furthermore, because ReplyBot keeps `2 * MAXPOSTS` during cleanup, but only collects `MAXPOSTS` comments on each loop, every comment the bot sees should be within the safe range with plenty of buffer.

Do your results not match this? Have you made any modifications to the bot? Can you provide some examples of where the bot messed up, and maybe upload the .db file somewhere ([pomf](https://pomf.is/) is easy)?

**Comment by voussoir** [comment]
Closing old issues.

**Comment by zatherz** [comment]
Oh wow. 4 years. Sorry for never responding, unfortunately I can't repro now ;)

**Comment by voussoir** [comment]
Yeah, time flies when you're having fun and avoiding the issues that need closing :)
