### ISSUE TITLE
ReplyBot

### ISSUE THREAD

**Issue by qwerty-space** [voussoir/reddit#6]
I'm fairly new to using GitHub, so I didn't know where else to put this.

I would like to change the ReplyBot to only reply to people in the KEYAUTHORS section as opposed to blacklisting them.  How would I go about doing this?

**Comment by voussoir** [comment]
Actually, that's what it does!

[line 82](https://github.com/voussoir/reddit/blob/master/ReplyBot/replybot.py#L82) says:

    all(auth.lower() != pauthor for auth in KEYAUTHORS):

This will check pauthor against each item in KEYAUTHORS, and if all of them are !=, then it proceeds onto the next line, which is `continue`.

Personally I've always felt that `continue` should have been called something else, because what it actually does is skip the rest of this loop and work on the next item. If you're assuming it means to move forward, that's where the misunderstanding is.

&nbsp;

If you have any other questions or need code modifications like this, you can [PM me on reddit](http://www.reddit.com/message/compose?to=GoldenSights&subject=IRC). That'll be better than a github issue.
