### ISSUE TITLE
Is there automated reddit poster bot ?

### ISSUE THREAD

**Issue by shtefcs** [voussoir/reddit#7]
Hi, I see u did alot of work with all ur bots. It's little bit hard for me to find trough all, so if u can point me is there any reddit poster bot ? 

What I mean is to pick up some source like xml, rss feed, json , and post from it ?

Peace,

**Comment by voussoir** [comment]
Sorry, I don't have any bots that use internet feeds like that. You may be able to use http://ifttt.com and create an RSS recipe to create posts though. I've never used it, but I know they have options for detecting new items and generating submissions. Would that work?

Otherwise, you should make a post on [/r/RequestABot](http://reddit.com/r/requestabot) and someone may help you out.

**Comment by shtefcs** [comment]
Thank you for your replay.
